// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Asp.Data;

#nullable disable

namespace Portfolio.Asp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Asp.Models.Academies.Academy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("academies");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Academies.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademyId")
                        .HasColumnType("integer");

                    b.Property<string>("CertigicateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FiledOfStudy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId");

                    b.ToTable("educations");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Academies.EducationSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.ToTable("educationsSkill");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Contacts.Contact", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("profileId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("profileId");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Projects.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Like")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Projects.ProjectCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectCategories");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Projects.ProjectMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMedia");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Projects.ProjectSubCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectCategoriesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCategoriesId");

                    b.ToTable("ProjectSubCategories");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Skills.SoftSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("SoftSkillCategory")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("SoftSkills");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Skills.Tools", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("toolCategory")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.SocialLinks.SocialLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("platform")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("socialLinks");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Users.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileVideo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.WorkExperiations.WorkExperiation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("profileid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("profileid");

                    b.ToTable("workExperiations");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.WorkExperiations.WorkExperiationSkills", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("WorkExperationId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkExperienceId")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("WorkExperienceId");

                    b.ToTable("WorkExperiationSkills");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.languages.language", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("level")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ProfileId");

                    b.ToTable("languages");
                });

            modelBuilder.Entity("ProfileTools", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("toolsId")
                        .HasColumnType("integer");

                    b.HasKey("ProfileId", "toolsId");

                    b.HasIndex("toolsId");

                    b.ToTable("ProfileTools");
                });

            modelBuilder.Entity("ProjectProjectSubCategories", b =>
                {
                    b.Property<int>("ProjectSubCategoriesId")
                        .HasColumnType("integer");

                    b.Property<int>("projectsId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectSubCategoriesId", "projectsId");

                    b.HasIndex("projectsId");

                    b.ToTable("ProjectProjectSubCategories");
                });

            modelBuilder.Entity("ProjectTools", b =>
                {
                    b.Property<int>("projectsId")
                        .HasColumnType("integer");

                    b.Property<int>("toolsId")
                        .HasColumnType("integer");

                    b.HasKey("projectsId", "toolsId");

                    b.HasIndex("toolsId");

                    b.ToTable("ProjectTools");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Academies.Academy", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Users.Profile", "Profile")
                        .WithMany("academies")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Academies.Education", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Academies.Academy", "Academy")
                        .WithMany("educations")
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academy");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Academies.EducationSkill", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Academies.Education", "Education")
                        .WithMany("Skills")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Education");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Contacts.Contact", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Users.Profile", "Profile")
                        .WithMany("contacts")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Projects.Project", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Users.Profile", "Profile")
                        .WithMany("projects")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Projects.ProjectMedia", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Projects.Project", "Project")
                        .WithMany("projectsMedia")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Projects.ProjectSubCategories", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Projects.ProjectCategories", "ProjectCategories")
                        .WithMany("ProjectSubCategories")
                        .HasForeignKey("ProjectCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectCategories");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Skills.SoftSkills", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Users.Profile", "Profile")
                        .WithMany("Skills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.SocialLinks.SocialLink", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Users.Profile", "Profile")
                        .WithMany("links")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Users.Profile", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Users.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Portfolio.Asp.Models.Users.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.WorkExperiations.WorkExperiation", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Users.Profile", "profile")
                        .WithMany("experiences")
                        .HasForeignKey("profileid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.WorkExperiations.WorkExperiationSkills", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.WorkExperiations.WorkExperiation", "WorkExperience")
                        .WithMany()
                        .HasForeignKey("WorkExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkExperience");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.languages.language", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Users.Profile", "Profile")
                        .WithMany("languages")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ProfileTools", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Users.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Asp.Models.Skills.Tools", null)
                        .WithMany()
                        .HasForeignKey("toolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectProjectSubCategories", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Projects.ProjectSubCategories", null)
                        .WithMany()
                        .HasForeignKey("ProjectSubCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Asp.Models.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("projectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectTools", b =>
                {
                    b.HasOne("Portfolio.Asp.Models.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("projectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Asp.Models.Skills.Tools", null)
                        .WithMany()
                        .HasForeignKey("toolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Academies.Academy", b =>
                {
                    b.Navigation("educations");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Academies.Education", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Projects.Project", b =>
                {
                    b.Navigation("projectsMedia");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Projects.ProjectCategories", b =>
                {
                    b.Navigation("ProjectSubCategories");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Users.Profile", b =>
                {
                    b.Navigation("Skills");

                    b.Navigation("academies");

                    b.Navigation("contacts");

                    b.Navigation("experiences");

                    b.Navigation("languages");

                    b.Navigation("links");

                    b.Navigation("projects");
                });

            modelBuilder.Entity("Portfolio.Asp.Models.Users.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
